server:
  port: 10110
spring:
  application:
    name: service-kill
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
    sentinel:
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            data-id: kill-service-flow-rule
            group-id: DEFAULT_GROUP
            namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
            rule-type: flow #这个是固定写法
      transport:
        dashboard: 127.0.0.1:8080
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 3000 # 连接超时 3 秒
            read-timeout: 5000 # 读取超时 5 秒
  config:
    import:
      - nacos:${spring.application.name}.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: root
      database: 0
      jedis:
        pool:
          min-idle: 2
          max-idle: 10
rocketmq:
  name-server: 127.0.0.1:9876 #nameserver地址
  # 是否开启自动配置
  producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    group: "kill-service-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2

