server:
  port: 10110
spring:
  application:
    name: service-kill
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
    sentinel:
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            data-id: kill-service-flow-rule
            group-id: DEFAULT_GROUP
            namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
            rule-type: flow #这个是固定写法
      transport:
        dashboard: 127.0.0.1:8080
  config:
    import:
      - nacos:${spring.application.name}.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: root
      database: 0
      jedis:
        pool:
          min-idle: 2
          max-idle: 10


