server:
  port: 10060
spring:
  application:
    name: service-course
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:10010/ymcc/uaa
  config:
    import:
      - nacos:${spring.application.name}.yml
      - nacos:share-config.yml?group=DEFAULT_GROUP
  # 允许Bean定义覆盖，解决Feign客户端重复注册问题
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.163.com   # 设置邮箱主机(服务商),这里使用QQ邮件服务器
    username: fythnu@163.com  # 设置用户名
    password: TVdJxWfVkBGNdbEJ # 设置密码，该处的密码是QQ邮箱开启SMTP的授权码而非QQ密码
    properties:
      mail:
        smtp:
          auth: true  # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
          starttls: #SMTP加密方式:连接到一个TLS保护连接
            enable: true
            required: true

mybatis-plus:
  mapper-locations: classpath:com/example/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl