server:
  port: 10050
spring:
  mail:
    host: smtp.163.com   # 设置邮箱主机(服务商),这里使用QQ邮件服务器
    username: fythnu@163.com  # 设置用户名
    password: TVdJxWfVkBGNdbEJ # 设置密码，该处的密码是QQ邮箱开启SMTP的授权码而非QQ密码
    properties:
      mail:
        smtp:
          auth: true  # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
          starttls: #SMTP加密方式:连接到一个TLS保护连接
            enable: true
            required: true
  main:
    allow-bean-definition-overriding: true  # 允许Bean定义覆盖
  application:
    name: service-common
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  config:
    import:
      - nacos:${spring.application.name}.yml
      - nacos:share-config.yml?group=DEFAULT_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/ymcc-common?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
 #单机配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: root
      jedis:
        pool:
          min-idle: 2
          max-idle: 10
sms:
  accessKeyId: LTAI5tBMMMn9GnHUkb7Zyf5z
  accessKeySecret: mYOhkB0yWdlx3Tj01Q44dBgPc5hxR4
  signName: 速通互联验证码
  templateCode: 100001

oss:
  akid: LTAI5tBMMMn9GnHUkb7Zyf5z
  akSecret: mYOhkB0yWdlx3Tj01Q44dBgPc5hxR4
  endpoint: oss-cn-shanghai.aliyuncs.com
  region: cn-shanghai
  bucketName: class-cloud