server:
  port: 10050
spring:
  application:
    name: service-common
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  config:
    import:
      - nacos:${spring.application.name}.yml
      - nacos:share-config.yml?group=DEFAULT_GROUP
 #单机配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: root
      jedis:
        pool:
          min-idle: 2
          max-idle: 10
sms:
  accessKeyId: LTAI5tBMMMn9GnHUkb7Zyf5z
  accessKeySecret: mYOhkB0yWdlx3Tj01Q44dBgPc5hxR4
  signName: 速通互联验证码
  templateCode: 100001

#redis高可用集群的客户端连接配置
#spring:
#  data:
#    redis:
#      cluster:
#        nodes: 127.0.0.1:6379,127.0.0.1:6380  #配置整个高可用集群半数以上的节点数。
#      password: root
#哨兵模式的客户端连接配置
#spring:
#  data:
#    redis:
#      sentinel:
#        master: mymaster   #哨兵配置时，sentinel monitor mymaster 127.0.0.1 6380 1
#        nodes: 127.0.0.1:26379  #哨兵节点ip：port
#      password: root #主从节点的连接密码




