server:
  port: 10100
spring:
  application:
    name: service-pay
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  config:
    import:
      - nacos:${spring.application.name}.yml

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ymcc-system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 2
#
#mybatis-plus:
#  mapper-locations: classpath:com/zz/mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl