server:
  port: 10100
spring:
  application:
    name: service-pay
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  config:
    import:
      - nacos:${spring.application.name}.yml
rocketmq:
  name-server: 127.0.0.1:9876 #nameserver地址
  # 是否开启自动配置
  producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    group: "order-service-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
