server:
  port: 10010
spring:
  application:
    name: service-gateway
  cloud: #注册到Nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  config:
    import:
      - nacos:${spring.application.name}.yml?group=SERVICE_GROUP
