server:
  port: 10070
spring:
  application:
    name: service-media
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  config:
    import:
      - nacos:${spring.application.name}.yml
rocketmq:
  name-server: 127.0.0.1:9876 #nameserver地址
  # 是否开启自动配置
  producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    group: "media-service-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2

media:
  upload-base-dir: "D:/upload/" #分片上传地址，如果media做进群部署。A   /opt/upload/a.mp4)    B（消费者推流a.mp4）   linux下通过NPS应用共享磁盘
  ffmpeg‐path: "G:/Java_Devlope/ffmpeg/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe" #ffmpeg视频工具安装地址
  rtmp: "rtmp://8.140.55.108:1935/live/" # 推流到云服务器的地址
  play: "http://8.140.55.108:8080/hls/live/" #播放地址
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ymcc-media?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 2
#
#mybatis-plus:
#  mapper-locations: classpath:com/example/mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl